# apiVersion: v1
# kind: Namespace
# metadata:
#   name: cert-manager
# ---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: kingdonb
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: cert-manager
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
    version: v0.16.1
  values:
    installCRDs: false
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: kingdonb
spec:
  acme:
    email: kingdon@teamhephy.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-letsencrypt-staging-key
    solvers:
    - http01:
        ingress:
          class: nginx
