# apiVersion: v1
# kind: Namespace
# metadata:
#   name: deis
# ---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: hephy
  namespace: kingdonb
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: hephy
  chart:
    git: git@github.com:kingdonb/gitops-hephy
    path: workflow
    ref: kingdonb
    skipDepUpdate: true
  values:
    global:
      storage: minio
      database_location: on-cluster
      use_rbac: true
      use_cni: true
      experimental_native_ingress: true
    controller:
      platform_domain: team.hephy.rocks
    router:
      host_port:
        enabled: false
