apiVersion: v1
kind: Namespace
metadata:
  name: deis
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: hephy
  namespace: deis
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: hephy
  chart:
    git: git@github.com:kingdonb/gitops-hephy
    path: workflow
    ref: master
  values:
    global:
      storage: minio
      database_location: on-cluster
      use_rbac: true
      use_cni: true
    router:
      host_port:
        enabled: true
