# apiVersion: v1
# kind: Namespace
# metadata:
#   name: nginx-ingress
# ---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress
  namespace: nginx-ingress
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: ingress
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: nginx-ingress
    version: 1.40.2
  values:
    tcp:
      2222: "deis/deis-builder:2222"
    controller:
      hostNetwork: true
      daemonSet:
        useHostPort: true
      kind: DaemonSet
      service:
        type: NodePort
