apiVersion: v1
kind: Namespace
metadata:
  name: oauth2-proxy
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: oauth2-proxy
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: oauth2-proxy
    version: 3.2.0
  values:
    config:
      existingSecret: hephynator-oauth2-secret
    extraArgs:
      provider: "github"
      github-team: "kingdon-ci"
    ingress:
      enabled: true
      path: /oauth2
      hosts:
        - hephynator.team.hephy.rocks
      annotations:
        kubernetes.io/ingress.class: nginx
        certmanager.io/cluster-issuer: letsencrypt-staging
      tls:
      - secretName: hephynator-tls
        hosts:
          - hephynator.team.hephy.rocks
